# Autogenerated wrapper script for HelloWorldMPIRust_jll for x86_64-w64-mingw32-mpi+microsoftmpi
export hello_world

using CompilerSupportLibraries_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("HelloWorldMPIRust")
JLLWrappers.@declare_executable_product(hello_world)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        hello_world,
        "bin\\hello_world.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
